/* Least-privilege setup: the API connects as hmis_app, which can ONLY execute
   the stored procedures — no SELECT/INSERT/UPDATE on tables, no schema rights.
   Swap the password before running. */
USE HMIS;
GO

IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = 'hmis_app')
  CREATE LOGIN hmis_app WITH PASSWORD = 'CHANGE_ME_Strong#Password1', CHECK_POLICY = ON;
GO

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'hmis_app')
  CREATE USER hmis_app FOR LOGIN hmis_app;
GO

-- No table access at all…
DENY SELECT, INSERT, UPDATE, DELETE ON SCHEMA::dbo TO hmis_app;
-- …only EXECUTE on procs and functions.
GRANT EXECUTE ON SCHEMA::dbo TO hmis_app;
GO

/* Seed users (bcrypt hashes are generated by the app; insert via sqlcmd once):
   INSERT INTO dbo.Users (Username, FullName, PassHash, RoleId) VALUES
     ('dr.Ravi',        N'Dr. Ravi Verma',  '<bcrypt-hash>', 1),
     ('nurse.meena',    N'Sr. Meena Joshi', '<bcrypt-hash>', 2),
     ('frontdesk.rahul',N'Rahul Sen',       '<bcrypt-hash>', 3),
     ('pharm.vikas',    N'Vikas Rao',       '<bcrypt-hash>', 4),
     ('admin.sk',       N'Dr. S. Kulkarni', '<bcrypt-hash>', 5);
   Generate a hash: cd server && node -e "import('bcryptjs').then(b=>console.log(b.hashSync('YourPassword',10)))"
*/
